### ISSUE TITLE
Clear functionality doesn't seem to work

### ISSUE THREAD

**Issue by victor-z-xiong** [ewyuan/music-player#3]
Workflow: 

Searched for "darude sandstorm". Played it. Then paused it. Cleared it from queue. Then added "remember me" from coco. When I typed resume it played darude sandstorm instead of "remember me".

Logs: 

Please enter the song you are searching for: darude sandstorm
Enter control option (Type 'help' for list of available options): help

add [song] - Adds [song] to the queue
clear - Clears the queue
pause - Pause the current song
resume - Resumes the current song
queue - Prints the current queue
skip - Plays the next song in queue
cur - Get the title of the current song
time - Get the time of the current song
prev - Get the title of the previous song
rewind - Restart the current song
remove [pos] - Removes the song in position [pos] from the q
exit - Exits the program

Enter control option (Type 'help' for list of available options): pause
Pausing 'Darude - Sandstorm'.
Enter control option (Type 'help' for list of available options): play
Option 'play' not supported.
Enter control option (Type 'help' for list of available options): resume
Resuming 'Darude - Sandstorm'.
Enter control option (Type 'help' for list of available options): pause
Pausing 'Darude - Sandstorm'.
Enter control option (Type 'help' for list of available options): resume
Resuming 'Darude - Sandstorm'.
Enter control option (Type 'help' for list of available options): play
Option 'play' not supported.
Enter control option (Type 'help' for list of available options): pause
Pausing 'Darude - Sandstorm'.
Enter control option (Type 'help' for list of available options): clear
Cleared the queue.
Enter control option (Type 'help' for list of available options): add remember me coco
Added 'remember me coco' to queue.
Enter control option (Type 'help' for list of available options): play
Option 'play' not supported.
Enter control option (Type 'help' for list of available options): resume
Resuming 'Darude - Sandstorm'.
Enter control option (Type 'help' for list of available options): skip
Skipping 'Darude - Sandstorm'.
Enter control option (Type 'help' for list of available options):

**Comment by EddyMaric** [comment]
When a song is playing, its not in the queue anymore. If you type queue while the song is paused youll see that it doesnt show in the queue.
